//
// Created by marci_000 on 04.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM18_USE_STD_UNIQUE_PTR_FOR_EXCLUSIVE_OWNERSHIP_RESOURCE_MANAGEMENT_H
#define EFFECTIVEMODERNCPP_ITEM18_USE_STD_UNIQUE_PTR_FOR_EXCLUSIVE_OWNERSHIP_RESOURCE_MANAGEMENT_H


class item18_use_std_unique_ptr_for_exclusive_ownership_resource_management {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM18_USE_STD_UNIQUE_PTR_FOR_EXCLUSIVE_OWNERSHIP_RESOURCE_MANAGEMENT_H
