//
// Created by marci_000 on 13.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM24_DISTINGUISH_UNIVERSAL_REFERENCES_FROM_RVALUE_REFERENCES_H
#define EFFECTIVEMODERNCPP_ITEM24_DISTINGUISH_UNIVERSAL_REFERENCES_FROM_RVALUE_REFERENCES_H


class item24_distinguish_universal_references_from_rvalue_references {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM24_DISTINGUISH_UNIVERSAL_REFERENCES_FROM_RVALUE_REFERENCES_H
