//
// Created by marci_000 on 11.04.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM35_PREFER_TASK_BASED_PROGRAMMING_TO_THREAD_BASED_H
#define EFFECTIVEMODERNCPP_ITEM35_PREFER_TASK_BASED_PROGRAMMING_TO_THREAD_BASED_H


class item35_prefer_task_based_programming_to_thread_based {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM35_PREFER_TASK_BASED_PROGRAMMING_TO_THREAD_BASED_H
