//
// Created by marci_000 on 24.03.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM30_FAMILIARIZE_YOURSELF_WITH_PERFECT_FORWARDING_FAILURE_CASES_H
#define EFFECTIVEMODERNCPP_ITEM30_FAMILIARIZE_YOURSELF_WITH_PERFECT_FORWARDING_FAILURE_CASES_H


class item30_familiarize_yourself_with_perfect_forwarding_failure_cases {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM30_FAMILIARIZE_YOURSELF_WITH_PERFECT_FORWARDING_FAILURE_CASES_H
