//
// Created by marci_000 on 23.03.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM29_ASSUME_THAT_MOVE_OPERATIONS_ARE_NOT_PRESENT_NOT_CHEAP_AND_NOT_USED_H
#define EFFECTIVEMODERNCPP_ITEM29_ASSUME_THAT_MOVE_OPERATIONS_ARE_NOT_PRESENT_NOT_CHEAP_AND_NOT_USED_H


class item29_assume_that_move_operations_are_not_present_not_cheap_and_not_used {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM29_ASSUME_THAT_MOVE_OPERATIONS_ARE_NOT_PRESENT_NOT_CHEAP_AND_NOT_USED_H
