//
// Created by marci_000 on 22.04.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM39_CONSIDER_VOID_FUTURES_FOR_ONE_SHOT_EVENT_COMMUNICATION_H
#define EFFECTIVEMODERNCPP_ITEM39_CONSIDER_VOID_FUTURES_FOR_ONE_SHOT_EVENT_COMMUNICATION_H


class item39_consider_void_futures_for_one_shot_event_communication {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM39_CONSIDER_VOID_FUTURES_FOR_ONE_SHOT_EVENT_COMMUNICATION_H
