//
// Created by marci_000 on 18.04.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM37_MAKE_STD_THREADS_UNJOINABLE_ON_ALL_PATHS_H
#define EFFECTIVEMODERNCPP_ITEM37_MAKE_STD_THREADS_UNJOINABLE_ON_ALL_PATHS_H


class item37_make_std_threads_unjoinable_on_all_paths {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM37_MAKE_STD_THREADS_UNJOINABLE_ON_ALL_PATHS_H
