//
// Created by marcin on 16.01.17.
//

#ifndef EFFECTIVEMODERNCPP_ITEM7_DISTINGUISH_BETWEEN_PARENTHESIS_AND_BRACES_WHEN_CREATING_OBJECTS_H
#define EFFECTIVEMODERNCPP_ITEM7_DISTINGUISH_BETWEEN_PARENTHESIS_AND_BRACES_WHEN_CREATING_OBJECTS_H


class item7_distinguish_between_parenthesis_and_braces_when_creating_objects {
public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM7_DISTINGUISH_BETWEEN_PARENTHESIS_AND_BRACES_WHEN_CREATING_OBJECTS_H
