//
// Created by marci_000 on 29.01.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM14_DECLARE_FUNCTIONS_NOEXCEPT_IF_THEY_WONT_EMIT_EXCEPTIONS_H
#define EFFECTIVEMODERNCPP_ITEM14_DECLARE_FUNCTIONS_NOEXCEPT_IF_THEY_WONT_EMIT_EXCEPTIONS_H


class item14_declare_functions_noexcept_if_they_wont_emit_exceptions {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM14_DECLARE_FUNCTIONS_NOEXCEPT_IF_THEY_WONT_EMIT_EXCEPTIONS_H
