//
// Created by marci_000 on 11.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM23_UNDERSTAND_STD_MOVE_AND_STD_FORWARD_H
#define EFFECTIVEMODERNCPP_ITEM23_UNDERSTAND_STD_MOVE_AND_STD_FORWARD_H


class item23_understand_std_move_and_std_forward {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM23_UNDERSTAND_STD_MOVE_AND_STD_FORWARD_H
