//
// Created by marcin on 30.04.17.
//

#ifndef EFFECTIVEMODERNCPP_ITEM42_CONSIDER_EMPLACEMENT_INSTEAD_OF_INSERTION_H
#define EFFECTIVEMODERNCPP_ITEM42_CONSIDER_EMPLACEMENT_INSTEAD_OF_INSERTION_H


class item42_consider_emplacement_instead_of_insertion {
public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM42_CONSIDER_EMPLACEMENT_INSTEAD_OF_INSERTION_H
