//
// Created by marci_000 on 22.03.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM28_UNDERSTAND_REFERENCE_COLLAPSING_H
#define EFFECTIVEMODERNCPP_ITEM28_UNDERSTAND_REFERENCE_COLLAPSING_H


class item28_understand_reference_collapsing {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM28_UNDERSTAND_REFERENCE_COLLAPSING_H
