//
// Created by marcin on 16.01.17.
//

#ifndef EFFECTIVEMODERNCPP_ITEM6_USE_THE_EXPLICITLY_TYPED_INITIALIZER_IDIOM_WHEN_AUTO_DEDUCES_UNDESIRED_TYPES_H
#define EFFECTIVEMODERNCPP_ITEM6_USE_THE_EXPLICITLY_TYPED_INITIALIZER_IDIOM_WHEN_AUTO_DEDUCES_UNDESIRED_TYPES_H


class item6_use_the_explicitly_typed_initializer_idiom_when_auto_deduces_undesired_types {
public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM6_USE_THE_EXPLICITLY_TYPED_INITIALIZER_IDIOM_WHEN_AUTO_DEDUCES_UNDESIRED_TYPES_H
