//
// Created by marci_000 on 27.04.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM40_USE_STD_ATOMIC_FOR_CONCURRENCY_VOLATILE_FOR_SPECIAL_MEMORY_H
#define EFFECTIVEMODERNCPP_ITEM40_USE_STD_ATOMIC_FOR_CONCURRENCY_VOLATILE_FOR_SPECIAL_MEMORY_H


class item40_use_std_atomic_for_concurrency_volatile_for_special_memory {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM40_USE_STD_ATOMIC_FOR_CONCURRENCY_VOLATILE_FOR_SPECIAL_MEMORY_H
