//
// Created by marci_000 on 03.04.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM32_USE_INIT_CAPTURE_TO_MOVE_OBJECTS_INTO_CLOSURES_H
#define EFFECTIVEMODERNCPP_ITEM32_USE_INIT_CAPTURE_TO_MOVE_OBJECTS_INTO_CLOSURES_H


class item32_use_init_capture_to_move_objects_into_closures {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM32_USE_INIT_CAPTURE_TO_MOVE_OBJECTS_INTO_CLOSURES_H
