//
// Created by marcin on 10.04.17.
//

#ifndef EFFECTIVEMODERNCPP_ITEM33_USE_DECLTYPE_ON_AUTO_REF_REF_PARAMETERS_TO_STD_FORWARD_THEM_H
#define EFFECTIVEMODERNCPP_ITEM33_USE_DECLTYPE_ON_AUTO_REF_REF_PARAMETERS_TO_STD_FORWARD_THEM_H


class item33_use_decltype_on_auto_ref_ref_parameters_to_std_forward_them {
public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM33_USE_DECLTYPE_ON_AUTO_REF_REF_PARAMETERS_TO_STD_FORWARD_THEM_H
