//
// Created by marci_000 on 08.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM21_PREFER_STD_MAKE_UNIQUE_AND_STD_MAKE_SHARED_TO_DIRECT_USE_OF_NEW_H
#define EFFECTIVEMODERNCPP_ITEM21_PREFER_STD_MAKE_UNIQUE_AND_STD_MAKE_SHARED_TO_DIRECT_USE_OF_NEW_H


class item21_prefer_std_make_unique_and_std_make_shared_to_direct_use_of_new {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM21_PREFER_STD_MAKE_UNIQUE_AND_STD_MAKE_SHARED_TO_DIRECT_USE_OF_NEW_H
