//
// Created by marci_000 on 21.04.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM38_BE_AWARE_OF_VARYING_THREAD_HANDLE_DESTRUCTOR_BEHAVIOR_H
#define EFFECTIVEMODERNCPP_ITEM38_BE_AWARE_OF_VARYING_THREAD_HANDLE_DESTRUCTOR_BEHAVIOR_H


class item38_be_aware_of_varying_thread_handle_destructor_behavior {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM38_BE_AWARE_OF_VARYING_THREAD_HANDLE_DESTRUCTOR_BEHAVIOR_H
