//
// Created by marci_000 on 19.01.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM12_DECLARE_OVERRIDING_FUNCTIONS_OVERRIDE_H
#define EFFECTIVEMODERNCPP_ITEM12_DECLARE_OVERRIDING_FUNCTIONS_OVERRIDE_H


class item12_declare_overriding_functions_override {
  public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM12_DECLARE_OVERRIDING_FUNCTIONS_OVERRIDE_H
