//
// Created by marci_000 on 28.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM26_AVOID_OVERLOADING_ON_UNIVERSAL_REFERENCES_H
#define EFFECTIVEMODERNCPP_ITEM26_AVOID_OVERLOADING_ON_UNIVERSAL_REFERENCES_H


class item26_avoid_overloading_on_universal_references {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM26_AVOID_OVERLOADING_ON_UNIVERSAL_REFERENCES_H
