//
// Created by marci_000 on 08.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM20_USE_STD_WEAK_PTR_FOR_STD_SHARED_PTR_LIKE_POINTERS_THAT_CAN_DANGLE_H
#define EFFECTIVEMODERNCPP_ITEM20_USE_STD_WEAK_PTR_FOR_STD_SHARED_PTR_LIKE_POINTERS_THAT_CAN_DANGLE_H


class item20_use_std_weak_ptr_for_std_shared_ptr_like_pointers_that_can_dangle {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM20_USE_STD_WEAK_PTR_FOR_STD_SHARED_PTR_LIKE_POINTERS_THAT_CAN_DANGLE_H
