//
// Created by marci_000 on 02.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM17_UNDERSTAND_SPECIAL_MEMBER_FUNCTION_GENERATION_H
#define EFFECTIVEMODERNCPP_ITEM17_UNDERSTAND_SPECIAL_MEMBER_FUNCTION_GENERATION_H


class item17_understand_special_member_function_generation {
public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM17_UNDERSTAND_SPECIAL_MEMBER_FUNCTION_GENERATION_H
