//
// Created by marci_000 on 07.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM19_USE_STD_SHARED_PTR_FOR_SHARED_OWNERSHIP_RESOURCE_MANAGEMENT_H
#define EFFECTIVEMODERNCPP_ITEM19_USE_STD_SHARED_PTR_FOR_SHARED_OWNERSHIP_RESOURCE_MANAGEMENT_H


class item19_use_std_shared_ptr_for_shared_ownership_resource_management {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM19_USE_STD_SHARED_PTR_FOR_SHARED_OWNERSHIP_RESOURCE_MANAGEMENT_H
