//
// Created by marci_000 on 17.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM25_USE_STD_MOVE_ON_RVALUE_REFERENCES_STD_FORWARD_ON_UNIVERSAL_REFERENCES_H
#define EFFECTIVEMODERNCPP_ITEM25_USE_STD_MOVE_ON_RVALUE_REFERENCES_STD_FORWARD_ON_UNIVERSAL_REFERENCES_H


class item25_use_std_move_on_rvalue_references_std_forward_on_universal_references {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM25_USE_STD_MOVE_ON_RVALUE_REFERENCES_STD_FORWARD_ON_UNIVERSAL_REFERENCES_H
