//
// Created by marcin on 11.01.17.
//

#ifndef EFFECTIVEMODERNCPP_ITEM11_PREFER_DELETED_FUNCTIONS_TO_PRIVATE_UNDEFINED_ONES_H
#define EFFECTIVEMODERNCPP_ITEM11_PREFER_DELETED_FUNCTIONS_TO_PRIVATE_UNDEFINED_ONES_H


class item11_prefer_deleted_functions_to_private_undefined_ones {
    public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM11_PREFER_DELETED_FUNCTIONS_TO_PRIVATE_UNDEFINED_ONES_H
