//
// Created by marcin on 18.04.17.
//

#ifndef EFFECTIVEMODERNCPP_ITEM36_SPECIFY_STD_LAUNCH_ASYNC_IF_ASYNCHRONICITY_IS_ESSENTIAL_H
#define EFFECTIVEMODERNCPP_ITEM36_SPECIFY_STD_LAUNCH_ASYNC_IF_ASYNCHRONICITY_IS_ESSENTIAL_H


class Item36_specify_std_launch_async_if_asynchronicity_is_essential {
public:
    void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM36_SPECIFY_STD_LAUNCH_ASYNC_IF_ASYNCHRONICITY_IS_ESSENTIAL_H
