//
// Created by marci_000 on 01.02.2017.
//

#ifndef EFFECTIVEMODERNCPP_ITEM16_MAKE_CONST_MEMBER_FUNCTIONS_THREAD_SAFE_H
#define EFFECTIVEMODERNCPP_ITEM16_MAKE_CONST_MEMBER_FUNCTIONS_THREAD_SAFE_H


class item16_make_const_member_functions_thread_safe {
 public:
  void run();
};


#endif //EFFECTIVEMODERNCPP_ITEM16_MAKE_CONST_MEMBER_FUNCTIONS_THREAD_SAFE_H
